### ISSUE TITLE
Clarity on distance from the camera frame

### ISSUE THREAD

**Issue by poornimajd** [pablopalafox/semantic-depth#8]
I got this from the paper
`On a gray stripe at the top of every frame, we printed out the estimated road’s width 10 m ahead, as well as the distance from the camera frame to the left and right ends of the road.`

I am not sure what is the meaning of computing the distance from the camera frame to the ends.Which is the point of reference exactly ,when you tell it is 3m to the left,1m to the right etc.,
Could you please clarify my doubt on this?
Thanks

**Comment by pablorpalafox** [comment]
hi @poornimajd, thanks for asking; essentially, the road's width, on the one hand, and adding up the distance from the camera center to the left and right ends of the road, on the other hand, should be the same. That is, the point of reference is the camera center. Let me know if it's still unclear.
